---
title: "Vis I"
output: github_document
---

```{r include=FALSE}
library(tidyverse)
library(ggridges)
```

import weather data

```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USW00022534", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2021-01-01",
    date_max = "2022-12-31") |>
  mutate(
    name = case_match(
      id, 
      "USW00094728" ~ "CentralPark_NY", 
      "USW00022534" ~ "Molokai_HI",
      "USS0023B17S" ~ "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10) |>
  select(name, id, everything())
```


making our first plot

```{r}
ggplot(weather_df, aes(x=tmin, y=tmax))+geom_point()
```

```{r}
weather_df %>% 
  ggplot(aes(x=tmin,y=tmax))+
  geom_point()
```

```{r}
ggp_weather_scatterplot =
  weather_df %>% 
  ggplot(aes(x=tmin,y=tmax))+
  geom_point()

ggp_weather_scatterplot
```

```{r}
weather_df %>% 
  filter(is.na(tmax))

```

## Fancier scatterplot 

```{r}
weather_df %>% 
  ggplot(aes(x= tmin,y=tmax,colour = name))+
  geom_point(alpha=.3, size = .8)+
  geom_smooth(se=FALSE)
```

where you define the aes matters 

```{r}
weather_df %>% 
  ggplot(aes(x= tmin,y=tmax))+
  geom_point(aes(colour = name),alpha=.3, size = .8)+
  geom_smooth(se=FALSE)
```


use faceting 

```{r}
weather_df %>% 
  ggplot(aes(x= tmin, y=tmax, colour = name))+
  geom_point(alpha=.3)+
  geom_smooth(se=FALSE)+
  facet_grid(.~name)
```

Lets male a somewhat mare intresting scatterplot 

```{r}
weather_df %>% 
  ggplot(aes(x=date,y=tmax,colour = name,size = prcp))+
  geom_point(alpha=.3)+
  geom_smooth(se=FALSE)+
  facet_grid(.~name)
```

## Learning assestment 

```{r}
weather_df %>% 
  filter(name=="CentralPark_NY") %>% 
  mutate(tempfmin = tmin* 9/5 + 32 ,tempfmax =tmax* 9/5 + 32 ) %>% 
  ggplot(aes(x= tempfmin,y=tempfmax))+
  geom_point()+
  geom_smooth(method = 'lm',se=FALSE)

```


```{r}
weather_df %>% 
  ggplot(aes(x= tmin,y=tmax))+
  geom_hex()
```

```{r}
weather_df %>% 
  ggplot(aes(x=tmin,y=tmax))+
  geom_point(color='blue')

```

## Unvarite plotss

```{r}
weather_df %>% 
  ggplot(aes(x=tmin,fill = name))+
  geom_histogram(position = 'dodge')
```

how would I fix this

```{r}
weather_df %>% 
  ggplot(aes(x=tmin,fill=name))+
  geom_histogram()+
  facet_grid(.~name)
```

maybe a density plot 

```{r}
weather_df %>% 
  ggplot(aes(x=tmin, fill= name))+
  geom_density(alpha=.3)
```

```{r}
weather_df %>% 
  ggplot(aes(x=name,y=tmin,fill = name))+
  geom_boxplot()
```

violin plotss

```{r}
weather_df %>% 
  ggplot(aes(x=name,y=tmin,fill =name))+
  geom_violin()
```

ridge plots

```{r}
weather_df %>% 
  ggplot(aes(x=tmin, y=name))+
  geom_density_ridges()
```

## Learning assesment 

```{r}
weather_df %>% 
  ggplot(aes(x=date,y=prcp,colour = name))+
  geom_point()
```

```{r}
weather_df %>% 
  ggplot(aes(x=name,y=prcp))+
  geom_boxplot()
```

```{r}
weather_df %>% 
  ggplot(aes(x=prcp)) +
  geom_histogram()
```

SAving and embending plots

```{r}
ggp_weather=
  weather_df %>% 
  ggplot(aes(x=date,y=tmax,colour = name))+
  geom_point()

ggsave('ggp_weather.pdf',ggp_weather,width = 8, height = 6)
```


```{r fig.width=6, fig.asp=.6}
weather_df %>% 
  ggplot(aes(x=date,y=tmax,colour = name))+
  geom_point()
```

