---
title: "Viz day 2"
author: "Miriam Lachs"
date: "2024-10-01"
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(patchwork)
library(haven)
```


import weather data

```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USW00022534", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2021-01-01",
    date_max = "2022-12-31") |>
  mutate(
    name = case_match(
      id, 
      "USW00094728" ~ "CentralPark_NY", 
      "USW00022534" ~ "Molokai_HI",
      "USS0023B17S" ~ "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10) |>
  select(name, id, everything())
```


make a scatter plot and fancy this time 

```{r}
weather_df %>% 
  ggplot(aes(x=tmin, y=tmax,colour = name))+
  geom_point(alpha =.3)+
  labs(
    title = "Temp Scatterplot",
    x = 'Minimum Temp (C)',
    y= 'MAximum Temp (C)',
    color = 'Location',
    caption = 'Weather data taken from rnoaa package from three stations'
  )
```


Scales -- start with 'x' and 'y' then do color 
```{r}
weather_df %>% 
  ggplot(aes(x=tmin, y=tmax,colour = name))+
  geom_point(alpha =.3)+
  labs(
    title = "Temp Scatterplot",
    x = 'Minimum Temp (C)',
    y= 'MAximum Temp (C)',
    color = 'Location',
    caption = 'Weather data taken from rnoaa package from three stations'
  )+ 
  scale_x_continuous(
    breaks = c(15,0,20),
    labels = c('-15C','0','20')
  )+
  scale_y_continuous(
    limits = c(0,30),
    transform = 'sqrt'
  )
```

Look at color 

```{r}
weather_df %>% 
  ggplot(aes(x=tmin, y=tmax,colour = name))+
  geom_point(alpha =.3)+
  labs(
    title = "Temp Scatterplot",
    x = 'Minimum Temp (C)',
    y= 'MAximum Temp (C)',
    color = 'Location',
    caption = 'Weather data taken from rnoaa package from three stations'
  )+ viridis::scale_color_viridis(discrete = TRUE)
```

## Themes

```{r}
ggp_scallterplot=
  weather_df %>% 
  ggplot(aes(x=tmin, y=tmax,colour = name))+
  geom_point(alpha =.3)+
  labs(
    title = "Temp Scatterplot",
    x = 'Minimum Temp (C)',
    y= 'MAximum Temp (C)',
    color = 'Location',
    caption = 'Weather data taken from rnoaa package from three stations'
  )+ viridis::scale_color_viridis(discrete = TRUE)
```

```{r}
ggp_scallterplot +
  theme(legend.position = 'bottom')
```

```{r}
ggp_scallterplot+
  theme_bw()+
  theme(legend.position = 'bottom')

```

order matters

```{r}
ggp_scallterplot +
  theme(legend.position = 'bottom')+
  theme_bw()
```

```{r}
ggp_scallterplot+
  theme_minimal()+
  theme(legend.position = 'bottom')
```


learnng assesment 
```{r}
weather_df %>% 
  ggplot(aes(x=date,y=tmax,colour = name))+
  geom_point(alpha=.3)+
  geom_smooth(se=FALSE)+
  labs(x = 'Date', 
       y = 'Maximum Temp (C)',
       title = 'Sasonal Variation in Max Temp')+
  viridis::scale_color_viridis(discrete = TRUE)+
  theme_minimal()+
  theme(legend.position = 'bottom')
```

extra bonus stuff in ggplot


use different data sets in different geoms
```{r}
cental_park_df = 
  weather_df %>% 
  filter(name=='CentralPark_NY')

molokai_df=
  weather_df %>% 
  filter(name=='Molokai_HI')

molokai_df %>% 
  ggplot(aes(x=date,y=tmax, color = name))+
  geom_point()+
  geom_line(data=cental_park_df)
```

multiple panals

```{r}

weather_df %>% 
  ggplot(aes(x=tmax,fill = name))+
  geom_density()+
  facet_grid(.~name)
```

```{r}
ggp_tmax_tmin =
  weather_df %>% 
  ggplot(aes(x=tmin,y=tmax,color=name))+
  geom_point(alpha=.3)

ggp_tmax_density =
  weather_df %>% 
  ggplot(aes(x=tmax,,fill=name))+
  geom_density(alpha=.3)

ggp_tmax_date_p = 
  weather_df |> 
  ggplot(aes(x = date, y = tmax, color = name)) + 
  geom_point(alpha = .5) +
  geom_smooth(se = FALSE) + 
  theme(legend.position = "bottom")
(ggp_tmax_tmin+ggp_tmax_density)/ggp_tmax_date_p
```

## Data manipulation 

```{r}
weather_df %>% 
  mutate(name=fct_relevel(name, c('Molokai_HI','CentralPark_NY','Waterhole_WA'))) %>% 
  ggplot(aes(x=name,y=tmax,fill = name))+
  geom_violin(alpha=.5)
```


PULSE data next

```{r}
pulse_df=
  read_sas('data_import_examples/public_pulse_data.sas7bdat') %>% 
  janitor::clean_names() %>% 
  pivot_longer(names_to = "visit",cols = 'bdi_score_bl':'bdi_score_12m',values_to = 'bdi_score',names_prefix = "bdi_score_") %>% 
  mutate(visit= ifelse(visit=='bl','00m',visit))

pulse_df%>% 
  ggplot(aes(x=visit,y=bdi_score))+
  geom_boxplot()
```

learning assesment FAS

```{r}
FAS_litters_df= 
  read_csv('data_import_examples/FAS_litters.csv') %>% 
  janitor::clean_names() %>%
  separate(group, into = c("dose", "treat_day"), sep = 3)

FAS_pups_df=
  read_csv('data_import_examples/FAS_pups.csv') %>% 
  janitor::clean_names()

FAS_df=
  FAS_litters_df %>% 
  full_join(FAS_pups_df,join_by(litter_number==litter_number))
```



```{r}
litter_data = 
  read_csv("data_import_examples//FAS_litters.csv", na = c("NA", ".", "")) |>
  janitor::clean_names() |>
  separate(group, into = c("dose", "day_of_tx"), sep = 3)

pup_data = 
  read_csv("data_import_examples//FAS_pups.csv", na = c("NA", ".", "")) |>
  janitor::clean_names() %>% 
  pivot_longer(cols = 'pd_ears':'pd_walk',names_to = 'outcome',values_to = 'pn_day',names_prefix = 'pd_')

FAS_df=
  left_join(pup_data,litter_data,by ='litter_number')

FAS_df %>% 
  drop_na(day_of_tx) %>% 
  ggplot(aes(x=dose,y=pn_day))+
  geom_boxplot()+
  facet_grid(day_of_tx~outcome)
```

